config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  # OmniAuth routes
  devise_scope :user do
    get '/users/auth/:provider/callback', to: 'users/omniauth_callbacks#callback'
    post '/users/auth/:provider/callback', to: 'users/omniauth_callbacks#callback'
    # Additional providers and routes can be added here
  end

  # Defines the root path route ("/")
  root 'books#index'

  resources :books
  resources :verses
  resources :chapters, only: %w[create destroy]
  resources :divisions

  get 'search_related_words', to: 'verses#search_related_words'
  get 'offline', to: 'home#offline', as: :offline
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :books

  self.per_page = 20

  def self.populate_division
    divisions = ['Books of the Law',
                 'Historical Books',
                 'Poetic Books',
                 'Major Prophets',
                 'Minor Prophets',
                 'The Gospels',
                 'The Historical Book',
                 'The Letters',
                 'The Book of Vision']

    divisions.each do |division|
      create!(division: division)
    end
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  include AdminAccessible

  before_action :set_division, only: %i[ show edit update destroy ]
  before_action :admin?

  # GET /divisions or /divisions.json
  def index
    @divisions = Division.paginate(page: params[:page])
  end

  # GET /divisions/1 or /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions or /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to division_url(@division), notice: "Division was successfully created." }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to division_url(@division), notice: "Division was successfully updated." }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url, notice: "Division was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_division
    @division = Division.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def division_params
    params.require(:division).permit(:division)
  end
end

app/views/divisions/_division.html.erb
<div id="<%= dom_id division %>">
  <p>
    <strong>Division:</strong>
    <%= division.division %>
  </p>

</div>

app/views/divisions/_form.html.erb
<div class="card mt-2 ">
    <div class="card-header">
      <h1>Create a New Division</h1>
    </div>
    <div class="card-body">
        <%= form_with(model: division) do |form| %>
          <% if division.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

              <ul>
                <% division.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group mb-4">
              <%= form.label :division, style: "display: block" %>
              <%= form.text_field :division, class: 'form-control'  %>
          </div>
          <div class="d-flex justify-content-center gap-3" >
              <%= form.submit "Create Division", class: 'btn btn-outline-success d-block flex-fill' %>
              <%= link_to "Back", books_path, class: 'btn btn-outline-primary d-block flex-fill' %>
          </div>
        <% end %>
    </div>
</div>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to "Show this division", @division %> |
  <%= link_to "Back to divisions", divisions_path %>
</div>

app/views/divisions/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Divisions</h1>
            <%= link_to 'Create New Division', new_division_path, class: 'btn btn-outline-primary' if admin? %>

            <div class="row" >
                <% @divisions.each do |division| %>
                        <div class="card mt-3 ">
                            <div class="card-body">
                                <h3><%= "#{division.division}" %></h3>
                                <br>
                                <%= link_to 'Show', division, class: 'btn btn-outline-primary' %>
                                <% if admin? %>
                                    <%= link_to 'Edit', edit_division_path(division), class: 'btn btn-outline-primary'  %>
                                    <%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary'  %>
                                <% end %>
                            </div>
                        </div>
                <% end %> 
                <div class="bb_pagination mb-4">
                    <div class="page_info mb-2">
                        <%= page_entries_info @divisions, {entry_name: 'division'} %>
                    </div> 
                    <%= will_paginate @divisions, :container => false %>
                </div>
            </div>
        </div>
</div>

app/views/divisions/new.html.erb
<div class="flex-row d-flex justify-content-center">
    <div class="col-md-8">

      <%= render "form", division: @division %>

      <br>

      <div class="d-flex justify-content-center gap-3" >
        <%= link_to "View Divisions", divisions_path, class: 'btn btn-success d-block flex-fill' %>
        <%= link_to "Home", root_path, class: 'btn btn-primary d-block flex-fill' %>
      </div>
  </div>
</div>

app/views/divisions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @division %>

<div>
<% if admin? %>
  <%= link_to "Edit this division", edit_division_path(@division) %> |
<% end %>
  <%= link_to "Back to divisions", divisions_path %>

  <%= button_to "Destroy this division", @division, method: :delete if admin? %>
</div>