config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  # OmniAuth routes
  devise_scope :user do
    get '/users/auth/:provider/callback', to: 'users/omniauth_callbacks#callback'
    post '/users/auth/:provider/callback', to: 'users/omniauth_callbacks#callback'
    # Additional providers and routes can be added here
  end

  # Defines the root path route ("/")
  root 'books#index'

  resources :books
  resources :verses
  resources :chapters, only: %w[create destroy]
  resources :divisions

  get 'search_related_words', to: 'verses#search_related_words'
  get 'offline', to: 'home#offline', as: :offline
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Bible Books</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <% if admin? %>
                <form class="form-inline d-flex ms-md-auto mt-2" action="/search_related_words">
                    <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success mx-2 my-2 my-sm-0" type="submit">Search</button>
                </form>
                <ul class="navbar-nav ms-md-auto">
                    <li class="nav-item active">
                        <%= link_to "Create Division", new_division_path, class: 'nav-link' %>
                    </li>

                    <li class="nav-item active">
                        <%= link_to "Create Book", new_book_path, class: 'nav-link' %>
                    </li>

                    <li class="nav-item active">
                        <%= link_to "Create Verse", new_verse_path, class: 'nav-link'  %>
                    </li>

                    <li class="nav-item active">
                        <%= link_to "Divisions", divisions_path, class: 'nav-link'  %>
                    </li>

                    <li class="nav-item active">
                        <%= link_to "Books", books_path, class: 'nav-link'  %>
                    </li>

                    <li class="nav-item active">
                        <%= link_to "Verses", verses_path, class: 'nav-link'  %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
                    </li>
                </ul>
            <% elsif member? %>
                <form class="form-inline d-flex ms-md-auto mt-2" action="/search_related_words">
                    <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success mx-2 my-2 my-sm-0" type="submit">Search</button>
                </form>
                <ul class="navbar-nav ms-md-auto">
                    <li class="nav-item active">
                        <%= link_to "Books", books_path, class: 'nav-link'  %>
                    </li>

                    <li class="nav-item active">
                        <%= link_to "Verses", verses_path, class: 'nav-link'  %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
                    </li>
                </ul>
            <% else %>
                <ul  class="navbar-nav ms-md-auto">
                    <li class="nav-item active">
                        <%= link_to "Books", books_path, class: 'nav-link'  %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to "Members Portal", new_user_session_path, class: 'nav-link'  %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to "Become a Member", new_user_registration_path, class: 'nav-link'  %>
                    </li>
                </ul>
            <% end%>
            </ul>
        </div>
    </div>
</nav>