config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  # OmniAuth routes
  devise_scope :user do
    get '/users/auth/:provider/callback', to: 'users/omniauth_callbacks#callback'
    post '/users/auth/:provider/callback', to: 'users/omniauth_callbacks#callback'
    # Additional providers and routes can be added here
  end

  # Defines the root path route ("/")
  root 'books#index'

  resources :books
  resources :verses
  resources :chapters, only: %w[create destroy]
  resources :divisions

  get 'search_related_words', to: 'verses#search_related_words'
  get 'offline', to: 'home#offline', as: :offline
end

app/models/book.rb
# app/models/book.rb
class Book < ApplicationRecord
  before_create :set_default_value

  has_many :chapters, dependent: :destroy
  has_many :verses
  has_many :notes

  belongs_to :division

  validates_numericality_of :no_of_chapter, greater_than_or_equal_to: 0

  self.per_page = 20

  def set_default_value
    self.division_id ||= 1
  end

  def self.populate_from_api
    return if Book.exists?

    response = HTTParty.get('https://bolls.life/get-books/NIV/')
    if response.success?
      data = JSON.parse(response.body)

      Book.transaction do
        data.each do |item|
          Book.create!(
            id: item['bookid'].to_i,
            title: item['name'],
            no_of_chapter: item['chapters'],
            description: 'No description at the moment',
            division_id: 1
          )
        end
      end
    else
      Rails.logger.error "Error: #{response.code}"
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include AdminAccessible

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :admin?, only: %i[new create edit update destroy]

  def index
    @divisions = Division.all
    div = params[:div]

    if !div.nil?
      @books = Book.where(:division_id => div).paginate(page: params[:page])
    else
      @books = Book.paginate(page: params[:page])
    end
  end

  def show
    # find the book we want to render
    @book = Book.find(params[:id])
    @chapters = Chapter.where(book_id: @book.id)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)

    if @book.save
      redirect_to @book # redirect to the newly created book
    else
      render :new
    end
    create_book_chapters
  end

  def create_book_chapters
    no_of_chapter = book_params[:no_of_chapter].to_i

    (1..no_of_chapter).each do |chapter_number|
      Chapter.create!(chapter_no: chapter_number,
                      book_id: @book.id)
    end
  end

  def update_book_chapters
    no_of_chapter = book_params[:no_of_chapter].to_i

    (1..no_of_chapter).each do |chapter_number|
      chapter = Chapter.where(book_id: @book.id, chapter_no: chapter_number)
      next if chapter.present?

      Chapter.create!(chapter_no: chapter_number,
                      book_id: @book.id)
    end
  end

  def delete_lingering_chapters
    no_of_chapter = book_params[:no_of_chapter].to_i
    chapter = Chapter.where(book_id: @book.id)

    return unless no_of_chapter < chapter.count

    (no_of_chapter + 1..chapter.count).each do |chapter_number|
      chapter.find_by(chapter_no: chapter_number).destroy
    end
  end

  def edit
    # find the book we want to render
    @book = Book.find(params[:id])
  end

  def update
    # find the book we want to render
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
    update_book_chapters
    delete_lingering_chapters
  end

  def destroy
    # find the book we want to render
    @book = Book.find(params[:id])

    @book.destroy
    redirect_to :action => :index
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :division_id, :no_of_chapter)
  end
end

app/views/books/_form.html.erb
<div class="flex-row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card mt-5 ">
            <div class="card-header">
              <h1>Create a New Book</h1>
            </div>
            <div class="card-body">
                <%= form_for @book do |f| %>
                    <div class="form-group mb-4">
                        <%= f.label :title %>
                        <%= f.text_field :title, class: 'form-control' %>
                    </div>
                    <div class="form-group mb-4">
                        <%= f.label :description %>
                        <%= f.text_area :description, class: 'form-control' %>
                    </div>
                    <div class="form-group mb-4">
                        <%= f.label 'Number of Chapters' %>
                        <%= f.number_field :no_of_chapter, class: 'form-control', min: 0 %>
                    </div>
                    <div class="form-group mb-4">
                        <%= f.label :division %> <br>
                        <%= f.select :division_id, Division.all.map {|d| [d.division, d.id]}, class: 'form-select d-block' %>
                    </div>
                    <div class="d-flex justify-content-center gap-3" >
                        <%= f.submit "Create Book", class: 'btn btn-outline-success d-block flex-fill' %>
                        <%= link_to "Back", books_path, class: 'btn btn-outline-primary d-block flex-fill' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="row" >
                <% @books.each do |book| %>
                    <div class="col-md-6">
                        <div class="card mt-3 ">
                            <%= link_to book_path(book.id), class: 'book-links' do %>
                                <div class="card-body">
                                    <h3><%= book.title%></h3>
                                </div>
                            <% end %>
                        </div>
                    </div>
                <% end %> 
                <div class="bb_pagination mb-4">
                    <div class="page_info mb-2">
                        <%= page_entries_info @books, {entry_name: 'Book'} %>
                    </div> 
                    <%= will_paginate @books, :container => false %>
                </div>
            </div>
        </div>
        <div class="col-md-4">  
            <div class="card mt-3">
                <div class="card-header">
                    Divisions
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <% @divisions.each do |division| %>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <%= link_to division.division, books_path(:div => division.id) %>
                            <span class="badge bg-primary rounded-pill"> <%= division.books.count %> </span>
                        </li>
                        <% end %>
                    </ul>
                </div> 
            </div>    
        </div>
    </div>
</div>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<div class="container-fluid mt-3">
    <% if @book.division.present? %>
        <h1>Division: <%=@book.division.division %></h1>
    <% end %>

    <h2><%= @book.title %></h2>

    <p><strong>Description: </strong><%= @book.description %></p>

    <% if user_signed_in? && admin?%>
        <%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-primary' %>
        <%= link_to "Delete", book_path(@book.id), method: :delete, class: 'btn btn-danger' %>
        <%= link_to "Back", books_path, class: 'btn btn-secondary' %>
    <% else %>
        <%= link_to "Back", books_path, class: 'btn btn-secondary' %>
    <% end%>

    <% @chapters.each do |chapter| %>
        <div class="accordion">
            <div class="accordion-item">
                <div class="accordion-item-header">
                     <h3>Chapter <%=chapter.chapter_no%></h3>
                </div>
                <div class="accordion-item-body">
                    <div class="accordion-item-body-content">
                        <% Verse.where(chapter_id: chapter.id, book_id: @book.id).each do |verse| %>
                            <p><strong>Verse <%=verse.verse_no%>:</strong> <%=verse.content.gsub("<br/>", " ")%></p>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<%= javascript_pack_tag 'accordion' %>